### ISSUE TITLE
url doesnt claim

### ISSUE THREAD

**Issue by localusers** [Don-Cryptus/DiscordCustomUrlSniper#1]
url doesnt claim any. tested on unknown urls/non claimed.

small fixes 2 be made.

**Comment by Don-Cryptus** [comment]
> url doesnt claim any. tested on unknown urls/non claimed.
> 
> small fixes 2 be made.

if you are getting error 429 Too Many Requests thats usually the fault of the proxies if you get status 200 and it doesnt work probably your token is faulty.

I tried it out myself again now seems to work fine
