### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Tritesson** [Don-Cryptus/DiscordCustomUrlSniper#2]
multiple tokens, when it is the only token, it gives an error 429.

The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting"). A Retry-After header might be included to this response indicating how long to wait before making a new request.

**Comment by Don-Cryptus** [comment]
> Tritesson

yes its a problem with the proxies u either put in paid one or you have to wait till it cycles to a working one

**Comment by Tritesson** [comment]
> > Tritesson
> 
> yes its a problem with the proxies u either put in paid one or you have to wait till it cycles to a working one

adedd multiple tokens?

**Comment by Don-Cryptus** [comment]
that doesnt matter if the ip is blocked remove the proxy section in each request and it will work but it takes your main ip
