### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by Tritesson** [Don-Cryptus/DiscordCustomUrlSniper#3]
It isn't working

**Comment by Don-Cryptus** [comment]
give me your server link where you are trying to get the link

**Comment by Tritesson** [comment]
asdfjnasdfjnasdf

its a status code 429

**Comment by Don-Cryptus** [comment]
do you even have 14 boosts on your server?

**Comment by Don-Cryptus** [comment]
![image](https://user-images.githubusercontent.com/70039285/176898205-bbd373c0-0fc8-4063-a0ce-d57701a99b82.png)
works fine for me

**Comment by Don-Cryptus** [comment]
Don Diabolic#4462

**Comment by Tritesson** [comment]
![image](https://user-images.githubusercontent.com/107753999/176898614-13328629-6735-494e-b529-9f4ac5435cfd.png)

**Comment by Don-Cryptus** [comment]
> ![image](https://user-images.githubusercontent.com/107753999/176898614-13328629-6735-494e-b529-9f4ac5435cfd.png)

I dont understand it

**Comment by Tritesson** [comment]
misnomer

**Comment by Don-Cryptus** [comment]
just add me on discord Don Diabolic#4462 or come to our server discord.gg/coding

**Comment by Don-Cryptus** [comment]
@Tritesson I made a new version fully redone
